server:
  port: 9000
  error:
    include-message: always
github:
  url: "https://api.github.com/users/{userLogin}"
webclient:
  connect:
    timeout: 3000
    reply: 4

calculation:
  followers:
    nominator: 6
  repos:
    incrementor: 2
