server:
  port: 9000
  error:
    include-message: always
github:
  url: "https://api.github.com/users/{userLogin}"
connect:
  timeout: 3000

calculation:
  followers:
    nominator: 6
  repos:
    incrementor: 2

#hystrix:
#  command:
#    fallbackcmd:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 4000